### ISSUE TITLE
Spoke Gateway tags do not support colons in key

### ISSUE THREAD

**Issue by wluo-xinja** [AviatrixSystems/terraform-provider-aviatrix#334]
For the Aviatrix Spoke Gateway (https://www.terraform.io/docs/providers/aviatrix/r/aviatrix_spoke_gateway.html)
When trying to provide tag names with a colon in them (e.g. Security:Zone) the key splits at the first colon. AWS (the only cloud provider supported at the moment) supports colons in the tag key which enables better categorisation of tags.

Given that AWS is the only provider that is supported, a different split character is needed. Valid tag characters are listed: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html#tag-restrictions

**Comment by inc1t3Ful** [comment]
Hi @wluo-xinja !

Thank you for bringing to our attention this issue! I will file this and notify the team. I will update you here accordingly for any followups.

**Comment by CyrusJavan** [comment]
Hello @wluo-xinja,

Thanks again for bringing up this issue. I agree that you should be able to utilize colon characters in your tags, however, that would be a breaking change and would require a major release to address this issue. At this time there is no timeline for our next major release. This issue is rooted in the way our backend API handles tags so the fix would be more involved than just a provider update. 

As a workaround at this time I would suggest using some of the other allowable non-alphanumeric characters to better categorize your tags.

**Comment by CyrusJavan** [comment]
@wluo-xinja As of provider version v2.19.0 you can use the `tags` attribute of aviatrix_spoke_gateway to have tags with colons in the key or value.
