### ISSUE TITLE
unable to create spoke gateway

### ISSUE THREAD

**Issue by tkellen** [AviatrixSystems/terraform-provider-aviatrix#41]
Hi all! Congrats on becoming an official terraform provider, I'm super excited to be using this :)

I attempted the following configuration about 20 minutes ago:
```
provider "aviatrix" {
  controller_ip           = "<OMITTED>"
  username                = "admin"
  password                = "<OMITTED>"
  skip_version_validation = true
}

resource "aviatrix_spoke_gateway" "main" {
  cloud_type   = 1
  account_name = "test"
  gw_name      = "test"
  vpc_id       = "vpc-<OMITTED>"
  vpc_reg      = "us-east-1"
  gw_size      = "t2.medium"
  subnet       = "10.11.9.0/28"
  ha_subnet    = "10.11.9.16/28"
  ha_gw_size   = "t2.medium"
}
```

..and received the following strange error response:
```
Error: a bool is required
```

I then tried to fill in every optional boolean attribute with my desired value in the hopes I'd get a successful apply but nothing worked. Can you please advise?

Thanks!

**Comment by inc1t3Ful** [comment]
Hi Tyler, thanks for trying out our provider!

I have just attempted to recreate your situation with the same configuration and did not hit any issues. Have you used our provider (sourcing through our AviatrixSystems github repo) prior to this? Issue may stem from Terraform building/ pulling updates from the wrong source.

**Comment by tkellen** [comment]
Thanks for the prompt reply @inc1t3Ful! Here's some more debugging output:

```
➜ terraform -version
Terraform v0.12.8

➜ terraform init

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "aviatrix" (terraform-providers/aviatrix) 2.2.0...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.aviatrix: version = "~> 2.2"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

➜ cat .terraform/plugins/linux_amd64/lock.json 
{
  "aviatrix": "91ab52ecd018ef256bfa15c8b03b70eaf9c7d064bb6b2a0e202c72dd6b55bc75"
}%                                                                                                                                                                                                                                             

➜ cat aviatrix-genenva-dev.tf 
provider "aviatrix" {
  controller_ip           = "<OMITTED>"
  username                = "<OMITTED>"
  password                = "<OMITTED>"
  skip_version_validation = true
}

resource "aviatrix_spoke_gateway" "main" {
  cloud_type   = 1
  account_name = "<OMITTED>"
  gw_name      = "<OMITTED>"
  vpc_id       = "<OMITTED>"
  vpc_reg      = "us-east-1"
  gw_size      = "t2.medium"
  subnet       = "10.11.9.0/28"
  ha_subnet    = "10.11.9.16/28"
  ha_gw_size   = "t2.medium"
}

➜ terraform apply

Error: a bool is required
```

**Comment by tkellen** [comment]
PS: yes, I used the plugin directly some months ago by cloning the repo and building locally and configuring terraform to use the result. I'm 99.9% sure I am using the correct upstream provider now, though.

**Comment by inc1t3Ful** [comment]
What version is your Controller? I just want to make sure the provider release (2.2, it seems) you are using is compatible with the Controller version. Because "skip_version_validation" is set to true, our provider cannot automatically catch if there is an issue there.

Could you also please provide the .tfstate file that was produced from running this 'terraform apply'? Omit any sensitive information, of course.

**Comment by tkellen** [comment]
My apologies, I really want to answer but I am on vacation for a week. I will follow up soon!

**Comment by MattSurabian** [comment]
Hi there, I can update while @tkellen is on vacation! The version of our controller is `UserConnect-5.0.2666` and it seems like as of provider version `2.3.36` this is working without the above error.

**Comment by inc1t3Ful** [comment]
Thanks for the update! Thats great news! I would still like to take a look at the .tfstate file produced from running the 'terraform apply', if you could provide that, in order to further debug.

Another thing I would like to mention is that we recommend that the 'version' be specified within the provider block in order to avoid any accidental updates/ compatibility issues between provider and Controller versions. This is because while 'version' is an optional parameter, if it is not specified, Terraform automatically pulls the latest version available without taking into account any possible issues that might occur

**Comment by MattSurabian** [comment]
Thanks for the note there, I'll make sure we do that. Since we were recently just playing around with this provider again we didn't hook up remote state like we have on the rest of our terraform projects so you may have to wait for @tkellen's return for the `.tfstate` from the run that failed. I can also try duplicating it on the older provider version later this week.

**Comment by tkellen** [comment]
Thanks ya'll!
