### ISSUE TITLE
Error Creating Spoke VPC for Azure

### ISSUE THREAD

**Issue by lctnstn** [AviatrixSystems/terraform-provider-aviatrix#500]
The config below:
```
resource "aviatrix_spoke_vpc" "foobar" {
  cloud_type   = 8
  account_name = "azure_account"
  gw_name      = "azure-spoke"
  vpc_id       = "/subscriptions/1-2-3-4-55/resourceGroups/foobar/providers/Microsoft.Network/virtualNetworks/foobar"
  vpc_reg      = "East US"
  vpc_size     = "t2.micro"
  subnet       = "10.1.0.0/24"
}
```

Returns this error:
`* aviatrix_spoke_vpc.foobar: failed to create Aviatrix Spoke VPC: Rest API create_spoke_gw Post failed: [Aviatrix Error] 'NoneType' object has no attribute 'address_space' Please validate your VNet and corresponding resource group input. (If this is not clear, go to docs.aviatrix.com and search the matching error string for resolution.)`

I am not attempting to use the attribute `address_space` in my config and am unsure where this error is coming from.

**Comment by iggynopolis** [comment]
Your error may be in the value you set for the "vpc_id" attribute. Rather than a path, you should input the Vnet Name:Resource Group. 
You can check for a valid vnet:resource group within the GUI when creating an aviatrix spoke gateway under Transit Network -> Setup -> Step 4. Setting Cloud Type to Azure ARM will show the vnets you can use for the vpc_id attribute

`# Example of Aviatrix arm spoke_vpc
resource "aviatrix_spoke_vpc" "test_spoke_vpc_arm" {
  cloud_type   = 8
  account_name = "my-arm"
  gw_name      = "spoke-gw-01"
  vpc_id       = "spoke:test-spoke-gw-123"
  vpc_reg      = "West US"
  vpc_size     = "t2.micro"
  subnet       = "10.13.0.0/24"
  enable_nat   = "no"
}`

**Comment by lctnstn** [comment]
@iggynopolis - That path is returned by the azurerm provider, accessed by calling `${azurerm_virtual_network.foobar.id}`. I don't believe Terraform provides a native way to retrieve the string as displayed in Aviatrix, so I'll have to compile the name another way. Thanks!

**Comment by lctnstn** [comment]
@arvindsree @iggynopolis - I was able to solve for the difference in the VPC ID field that Aviatrix uses vs. Azure ARM as follows:

```
resource "aviatrix_spoke_vpc" "foobar" {
  cloud_type   = 8
  account_name = "azure_account"
  gw_name      = "azure-spoke"
  vpc_id       = "${format("%s:%s", azurerm_virtual_network.foobar.name, azurerm_virtual_network.foobar.resource_group_name)}"
  vpc_reg      = "East US"
  vpc_size     = "t2.micro"
  subnet       = "10.1.0.0/24"
}
```

**Comment by arvindsree** [comment]
Nice.. you can also do it with the subnet as
"${azurerm_subnet.foobar.virtual_network_name}:${azurerm_subnet.foobar.resource_group_name}"
